[General]
priority = 100
description = Analog Mode (Headphone/Speaker 100%)

[Element Master]
volume = 100
switch = on

[Element PCM]
volume = 100
switch = on

[Element Headphone] # required for speakers plugged in from headphone jack
volume = 100
switch = on
required-any = any

[Element Speaker] # in case the device has a built-in speaker
volume = 100
switch = on
required-any = any

[Element Line Out] # in case the device has a line out
volume = 100
switch = on
required-any = any
