[General]
auto-profiles = yes
priority = 1000
description = Audio Profile

[Mapping analog-output]
device-strings = hw:%f
description = Analog Output
paths-output = analog-output
channel-map = left,right
priority = 100
direction = output

[Profile output:analog]
description = Analog Output
output-mappings = analog-output
priority = 1000
