[Seat:*]
autologin-user=user
autologin-user-timeout=0
autologin-session=minimal
greeter-hide-users=true
greeter-show-manual-login=false
greeter-allow-guest=false

[SeatDefaults]
autologin-user=user
autologin-user-timeout=0
autologin-session=minimal
